package com.mycompany.curriculo2;

import javax.swing.JOptionPane;

// Milena Bregalda
// Trabalho de 29/02/2024 até 08/03/2024 - Currículo (JFrame Form + Tabbed Pane)

public class Painel2 extends javax.swing.JFrame {

    /**
     * Creates new form Painel2
     */
    public Painel2() {
        initComponents();
        abas.setEnabledAt(1, false);
        abas.setEnabledAt(2, false);
        abas.setEnabledAt(3, false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        aba1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        botaoAba1 = new javax.swing.JButton();
        labelSobrenome = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCEP = new javax.swing.JLabel();
        labelDataNasc = new javax.swing.JLabel();
        labelNacionalidade = new javax.swing.JLabel();
        labelEstadoCivil = new javax.swing.JLabel();
        campoCNH = new javax.swing.JTextField();
        labelCNH = new javax.swing.JLabel();
        campoNacionalidade = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoCEP = new javax.swing.JTextField();
        campoEstado = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        campoSobrenome = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoEstadoCivil = new javax.swing.JComboBox<>();
        campoDataNasc2 = new javax.swing.JComboBox<>();
        campoDataNasc1 = new javax.swing.JComboBox<>();
        campoDataNasc3 = new javax.swing.JComboBox<>();
        botaoFoto = new javax.swing.JButton();
        aba2 = new javax.swing.JPanel();
        botaoAba2 = new javax.swing.JButton();
        labelCampoEstudo = new javax.swing.JLabel();
        campoCampoEstudo = new javax.swing.JTextField();
        labelSituacao = new javax.swing.JLabel();
        labelDataInicio = new javax.swing.JLabel();
        campoLocalInst = new javax.swing.JTextField();
        labelLocalInst = new javax.swing.JLabel();
        labelInst = new javax.swing.JLabel();
        campoInst = new javax.swing.JTextField();
        labelDiploma = new javax.swing.JLabel();
        campoDiploma = new javax.swing.JTextField();
        labelDataTermino = new javax.swing.JLabel();
        campoDataInicioFR2 = new javax.swing.JComboBox<>();
        campoDataInicioFR1 = new javax.swing.JComboBox<>();
        campoDataTerminoFR2 = new javax.swing.JComboBox<>();
        campoDataTerminoFR1 = new javax.swing.JComboBox<>();
        campoSituacao = new javax.swing.JComboBox<>();
        aba3 = new javax.swing.JPanel();
        botaoAba3 = new javax.swing.JButton();
        campoEmpregador = new javax.swing.JTextField();
        labelEmpregador = new javax.swing.JLabel();
        labelTituloCargo = new javax.swing.JLabel();
        campoTituloCargo = new javax.swing.JTextField();
        labelCidade2 = new javax.swing.JLabel();
        campoCidade2 = new javax.swing.JTextField();
        labelEstado2 = new javax.swing.JLabel();
        campoEstado2 = new javax.swing.JTextField();
        labelDataInicio22 = new javax.swing.JLabel();
        labelDataTermino22 = new javax.swing.JLabel();
        caixaTrabalhoAgora = new javax.swing.JCheckBox();
        campoDataInicioEP1 = new javax.swing.JComboBox<>();
        campoDataInicioEP2 = new javax.swing.JComboBox<>();
        campoDataInicioEP3 = new javax.swing.JComboBox<>();
        campoDataTerminoEP1 = new javax.swing.JComboBox<>();
        campoDataTerminoEP2 = new javax.swing.JComboBox<>();
        campoDataTerminoEP3 = new javax.swing.JComboBox<>();
        aba4 = new javax.swing.JPanel();
        botaoAba4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoResumo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setText("Nome");

        botaoAba1.setText("Próximo");
        botaoAba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAba1ActionPerformed(evt);
            }
        });

        labelSobrenome.setText("Sobrenome");

        labelEndereco.setText("Endereço");

        labelCidade.setText("Cidade");

        labelEstado.setText("Estado");

        labelCEP.setText("CEP");

        labelDataNasc.setText("Data de nascimento");

        labelNacionalidade.setText("Nacionalidade");

        labelEstadoCivil.setText("Estado civil");

        campoCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCNHActionPerformed(evt);
            }
        });

        labelCNH.setText("Carteira Nacional de Habilitação (CNH)");

        labelTelefone.setText("Telefone");

        labelEmail.setText("E-mail");

        campoSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSobrenomeActionPerformed(evt);
            }
        });

        campoEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro", "Casado", "Divorciado", "União Estável" }));
        campoEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoCivilActionPerformed(evt);
            }
        });

        campoDataNasc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        campoDataNasc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataNasc2ActionPerformed(evt);
            }
        });

        campoDataNasc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        campoDataNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataNasc1ActionPerformed(evt);
            }
        });

        campoDataNasc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        campoDataNasc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataNasc3ActionPerformed(evt);
            }
        });

        botaoFoto.setText("COLOCAR FOTO");

        javax.swing.GroupLayout aba1Layout = new javax.swing.GroupLayout(aba1);
        aba1.setLayout(aba1Layout);
        aba1Layout.setHorizontalGroup(
            aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aba1Layout.createSequentialGroup()
                        .addComponent(campoTelefone)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba1Layout.createSequentialGroup()
                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(aba1Layout.createSequentialGroup()
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(aba1Layout.createSequentialGroup()
                                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEstadoCivil)
                                            .addComponent(labelTelefone))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(aba1Layout.createSequentialGroup()
                                        .addComponent(campoDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(campoDataNasc2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoDataNasc3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail)
                                    .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botaoAba1)
                                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelNacionalidade)
                                            .addComponent(labelCNH)
                                            .addComponent(campoCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                            .addComponent(campoNacionalidade)
                                            .addComponent(campoEmail)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aba1Layout.createSequentialGroup()
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCidade)
                                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEstado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCEP)
                                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(aba1Layout.createSequentialGroup()
                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataNasc)
                            .addGroup(aba1Layout.createSequentialGroup()
                                .addComponent(botaoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEndereco)
                                    .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoEndereco)
                                        .addGroup(aba1Layout.createSequentialGroup()
                                            .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelNome))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelSobrenome)
                                                .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        aba1Layout.setVerticalGroup(
            aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(aba1Layout.createSequentialGroup()
                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(labelSobrenome))
                        .addGap(3, 3, 3)
                        .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(labelEstado)
                    .addComponent(labelCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNasc)
                    .addComponent(labelNacionalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataNasc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataNasc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCNH, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEstadoCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCNH)
                    .addComponent(campoEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(botaoAba1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        abas.addTab("Dados Pessoais", aba1);

        botaoAba2.setText("Próximo");
        botaoAba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAba2ActionPerformed(evt);
            }
        });

        labelCampoEstudo.setText("Campo de estudo");

        labelSituacao.setText("Situação");

        labelDataInicio.setText("Data de início");

        labelLocalInst.setText("Local de instituição de ensino");

        labelInst.setText("Instituição de ensino");

        labelDiploma.setText("Diploma");

        labelDataTermino.setText("Data de término");

        campoDataInicioFR2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        campoDataInicioFR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioFR2ActionPerformed(evt);
            }
        });

        campoDataInicioFR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        campoDataInicioFR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioFR1ActionPerformed(evt);
            }
        });

        campoDataTerminoFR2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        campoDataTerminoFR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataTerminoFR2ActionPerformed(evt);
            }
        });

        campoDataTerminoFR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        campoDataTerminoFR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataTerminoFR1ActionPerformed(evt);
            }
        });

        campoSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Formado", "Matriculado", "Trancado", "Desistente" }));

        javax.swing.GroupLayout aba2Layout = new javax.swing.GroupLayout(aba2);
        aba2.setLayout(aba2Layout);
        aba2Layout.setHorizontalGroup(
            aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aba2Layout.createSequentialGroup()
                        .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDiploma)
                            .addComponent(campoDiploma, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aba2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelCampoEstudo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(aba2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCampoEstudo)
                                .addContainerGap())))
                    .addGroup(aba2Layout.createSequentialGroup()
                        .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aba2Layout.createSequentialGroup()
                                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelInst)
                                    .addComponent(campoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(aba2Layout.createSequentialGroup()
                                        .addComponent(labelLocalInst)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(campoLocalInst)))
                            .addGroup(aba2Layout.createSequentialGroup()
                                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSituacao)
                                    .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(aba2Layout.createSequentialGroup()
                                        .addComponent(campoDataInicioFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDataInicioFR2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelDataInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(aba2Layout.createSequentialGroup()
                                        .addComponent(campoDataTerminoFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDataTerminoFR2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelDataTermino))
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoAba2)
                                .addGap(15, 15, 15)))
                        .addContainerGap())))
        );
        aba2Layout.setVerticalGroup(
            aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInst)
                    .addComponent(labelLocalInst))
                .addGap(3, 3, 3)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLocalInst, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiploma)
                    .addComponent(labelCampoEstudo))
                .addGap(3, 3, 3)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDiploma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCampoEstudo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSituacao)
                    .addComponent(labelDataInicio)
                    .addComponent(labelDataTermino))
                .addGap(2, 2, 2)
                .addGroup(aba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataInicioFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataInicioFR2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataTerminoFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataTerminoFR2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(botaoAba2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        abas.addTab("Formação", aba2);

        botaoAba3.setText("Próximo");
        botaoAba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAba3ActionPerformed(evt);
            }
        });

        labelEmpregador.setText("Empregador");

        labelTituloCargo.setText("Título do cargo");

        labelCidade2.setText("Cidade");

        labelEstado2.setText("Estado");

        labelDataInicio22.setText("Data de início");

        labelDataTermino22.setText("Data de término");

        caixaTrabalhoAgora.setText("Eu trabalho aqui no momento.");
        caixaTrabalhoAgora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTrabalhoAgoraActionPerformed(evt);
            }
        });

        campoDataInicioEP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        campoDataInicioEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioEP1ActionPerformed(evt);
            }
        });

        campoDataInicioEP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        campoDataInicioEP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioEP2ActionPerformed(evt);
            }
        });

        campoDataInicioEP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        campoDataInicioEP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataInicioEP3ActionPerformed(evt);
            }
        });

        campoDataTerminoEP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        campoDataTerminoEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataTerminoEP1ActionPerformed(evt);
            }
        });

        campoDataTerminoEP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        campoDataTerminoEP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataTerminoEP2ActionPerformed(evt);
            }
        });

        campoDataTerminoEP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        campoDataTerminoEP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataTerminoEP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aba3Layout = new javax.swing.GroupLayout(aba3);
        aba3.setLayout(aba3Layout);
        aba3Layout.setHorizontalGroup(
            aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aba3Layout.createSequentialGroup()
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataInicio22)
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addComponent(campoDataInicioEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDataInicioEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDataInicioEP3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(labelDataTermino22))
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botaoAba3)
                                    .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caixaTrabalhoAgora)
                                        .addGroup(aba3Layout.createSequentialGroup()
                                            .addComponent(campoDataTerminoEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(campoDataTerminoEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(campoDataTerminoEP3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(aba3Layout.createSequentialGroup()
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloCargo)
                            .addComponent(campoTituloCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelEmpregador))
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEmpregador, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                    .addGroup(aba3Layout.createSequentialGroup()
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCidade2)
                            .addComponent(campoCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelEstado2))
                            .addGroup(aba3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEstado2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        aba3Layout.setVerticalGroup(
            aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloCargo)
                    .addComponent(labelEmpregador))
                .addGap(3, 3, 3)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTituloCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmpregador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade2)
                    .addComponent(labelEstado2))
                .addGap(3, 3, 3)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataInicio22)
                    .addComponent(labelDataTermino22))
                .addGap(2, 2, 2)
                .addGroup(aba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataInicioEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataInicioEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataInicioEP3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataTerminoEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataTerminoEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataTerminoEP3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(caixaTrabalhoAgora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(botaoAba3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        abas.addTab("Experiências profissionais", aba3);

        botaoAba4.setText("Salvar");
        botaoAba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAba4ActionPerformed(evt);
            }
        });

        campoResumo.setColumns(20);
        campoResumo.setRows(5);
        jScrollPane1.setViewportView(campoResumo);

        javax.swing.GroupLayout aba4Layout = new javax.swing.GroupLayout(aba4);
        aba4.setLayout(aba4Layout);
        aba4Layout.setHorizontalGroup(
            aba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aba4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(aba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba4Layout.createSequentialGroup()
                        .addComponent(botaoAba4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        aba4Layout.setVerticalGroup(
            aba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aba4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAba4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        abas.addTab("Resumo", aba4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAba1ActionPerformed
        abas.setSelectedIndex(1);
        abas.setEnabledAt(1, true);
    }//GEN-LAST:event_botaoAba1ActionPerformed

    private void campoEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstadoCivilActionPerformed

    private void campoDataNasc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataNasc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNasc2ActionPerformed

    private void campoDataNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataNasc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNasc1ActionPerformed

    private void campoDataNasc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataNasc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNasc3ActionPerformed

    private void botaoAba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAba2ActionPerformed
        abas.setSelectedIndex(2);
        abas.setEnabledAt(2, true);
    }//GEN-LAST:event_botaoAba2ActionPerformed

    private void botaoAba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAba3ActionPerformed
        Arquivo a = new Arquivo();

        String dados = "---------------------------------------------------\n";
        dados += "Dados pessoais\n\n";
        dados += "Nome: " + campoNome.getText() + "\n";
        dados += "Sobrenome: " + campoSobrenome.getText() + "\n";
        dados += "Endereço: " + campoEndereco.getText() + "\n";
        dados += "Cidade: " + campoCidade.getText() + "\n";
        dados += "Estado: " + campoEstado.getText() + "\n";
        dados += "CEP: " + campoCEP.getText() + "\n";
        dados += "Telefone: " + campoTelefone.getText() + "\n";
        dados += "E-mail: " + campoEmail.getText() + "\n";
        dados += "Data de nascimento: " + campoDataNasc1.getSelectedItem() + " de " + campoDataNasc2.getSelectedItem() + " de " + campoDataNasc3.getSelectedItem() + "\n";
        dados += "Nacionalidade: " + campoNacionalidade.getText() + "\n";
        dados += "Estado civil: " + campoEstadoCivil.getSelectedItem() + "\n";
        dados += "Carteira Nacional de Habilitação (CNH): " + campoCNH.getText() + "\n";

        dados += "\n---------------------------------------------------\n";
        dados += "Formação\n\n";
        dados += "Instituição de ensino: " + campoInst.getText() + "\n";
        dados += "Local de instituição de ensino: " + campoLocalInst.getText() + "\n";
        dados += "Diploma: " + campoDiploma.getText() + "\n";
        dados += "Campo de estudo: " + campoCampoEstudo.getText() + "\n";
        dados += "Situação: " + campoSituacao.getSelectedItem() + "\n";
        dados += "Data de início: " + campoDataInicioFR1.getSelectedItem() + " de " + campoDataInicioFR2.getSelectedItem() + "\n";
        dados += "Data de término: " + campoDataTerminoFR1.getSelectedItem() + " de " + campoDataTerminoFR2.getSelectedItem() + "\n";

        dados += "\n---------------------------------------------------\n";
        dados += "Experiências profissionais\n\n";
        dados += "Título do cargo: " + campoTituloCargo.getText() + "\n";
        dados += "Empregador: " + campoEmpregador.getText() + "\n";
        dados += "Cidade: " + campoCidade2.getText() + "\n";
        dados += "Estado: " + campoEstado2.getText() + "\n";
        dados += "Data de início: " + campoDataInicioEP1.getSelectedItem() + " de " + campoDataInicioEP2.getSelectedItem() + " de " + campoDataInicioEP3.getSelectedItem() + "\n";
        dados += "Data de término: " + campoDataTerminoEP1.getSelectedItem() + " de " + campoDataTerminoEP2.getSelectedItem() + " de " + campoDataTerminoEP3.getSelectedItem() + "\n";

        if (caixaTrabalhoAgora.isSelected()) {
            dados += "Trabalha aqui no momento: SIM\n";
        } else {
            dados += "Trabalha aqui no momento: NÃO\n";
        }

        dados += "\n---------------------------------------------------\n";

        a.gravar(dados);
        String textoResumo = a.ler();
        campoResumo.setText(textoResumo);
        
        abas.setSelectedIndex(3);
        abas.setEnabledAt(3, true);
    }//GEN-LAST:event_botaoAba3ActionPerformed

    private void caixaTrabalhoAgoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTrabalhoAgoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTrabalhoAgoraActionPerformed

    private void campoSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSobrenomeActionPerformed

    private void campoDataInicioFR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioFR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioFR2ActionPerformed

    private void campoDataInicioFR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioFR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioFR1ActionPerformed

    private void campoDataTerminoFR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataTerminoFR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataTerminoFR2ActionPerformed

    private void campoDataTerminoFR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataTerminoFR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataTerminoFR1ActionPerformed

    private void campoDataInicioEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioEP1ActionPerformed

    private void campoDataInicioEP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioEP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioEP2ActionPerformed

    private void campoDataInicioEP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataInicioEP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataInicioEP3ActionPerformed

    private void campoDataTerminoEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataTerminoEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataTerminoEP1ActionPerformed

    private void campoDataTerminoEP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataTerminoEP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataTerminoEP2ActionPerformed

    private void campoDataTerminoEP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataTerminoEP3ActionPerformed
        botaoAba1.setEnabled(true);
    }//GEN-LAST:event_campoDataTerminoEP3ActionPerformed

    private void campoCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCNHActionPerformed

    private void botaoAba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAba4ActionPerformed
        JOptionPane.showMessageDialog(null,
                "Salvo com sucesso!", "Mensagem",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botaoAba4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aba1;
    private javax.swing.JPanel aba2;
    private javax.swing.JPanel aba3;
    private javax.swing.JPanel aba4;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton botaoAba1;
    private javax.swing.JButton botaoAba2;
    private javax.swing.JButton botaoAba3;
    private javax.swing.JButton botaoAba4;
    private javax.swing.JButton botaoFoto;
    private javax.swing.JCheckBox caixaTrabalhoAgora;
    private javax.swing.JTextField campoCEP;
    private javax.swing.JTextField campoCNH;
    private javax.swing.JTextField campoCampoEstudo;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCidade2;
    private javax.swing.JComboBox<String> campoDataInicioEP1;
    private javax.swing.JComboBox<String> campoDataInicioEP2;
    private javax.swing.JComboBox<String> campoDataInicioEP3;
    private javax.swing.JComboBox<String> campoDataInicioFR1;
    private javax.swing.JComboBox<String> campoDataInicioFR2;
    private javax.swing.JComboBox<String> campoDataNasc1;
    private javax.swing.JComboBox<String> campoDataNasc2;
    private javax.swing.JComboBox<String> campoDataNasc3;
    private javax.swing.JComboBox<String> campoDataTerminoEP1;
    private javax.swing.JComboBox<String> campoDataTerminoEP2;
    private javax.swing.JComboBox<String> campoDataTerminoEP3;
    private javax.swing.JComboBox<String> campoDataTerminoFR1;
    private javax.swing.JComboBox<String> campoDataTerminoFR2;
    private javax.swing.JTextField campoDiploma;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEmpregador;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoEstado2;
    private javax.swing.JComboBox<String> campoEstadoCivil;
    private javax.swing.JTextField campoInst;
    private javax.swing.JTextField campoLocalInst;
    private javax.swing.JTextField campoNacionalidade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextArea campoResumo;
    private javax.swing.JComboBox<String> campoSituacao;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoTituloCargo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCNH;
    private javax.swing.JLabel labelCampoEstudo;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade2;
    private javax.swing.JLabel labelDataInicio;
    private javax.swing.JLabel labelDataInicio22;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelDataTermino;
    private javax.swing.JLabel labelDataTermino22;
    private javax.swing.JLabel labelDiploma;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmpregador;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelEstado2;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelInst;
    private javax.swing.JLabel labelLocalInst;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSituacao;
    private javax.swing.JLabel labelSobrenome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTituloCargo;
    // End of variables declaration//GEN-END:variables
}
