package com.mycompany.milenatrabalho2;

import javax.swing.JOptionPane;

// Milena Bregalda
// Trabalho de 04/03/2024 - Planejar e implementar própria interface
// com JPanel Form (Pesquisa de satisfação Senac Tech)

public class Interface extends javax.swing.JPanel {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCursos = new javax.swing.ButtonGroup();
        grupoSatisfacao = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelCurso = new javax.swing.JLabel();
        opcaoTI = new javax.swing.JRadioButton();
        opcaoTDS = new javax.swing.JRadioButton();
        opcaoAdm = new javax.swing.JRadioButton();
        labelMaterias = new javax.swing.JLabel();
        opcaoMtSatisfeito = new javax.swing.JRadioButton();
        opcaoSatisfeito = new javax.swing.JRadioButton();
        opcaoInsatisfeito = new javax.swing.JRadioButton();
        labelNivel = new javax.swing.JLabel();
        labelObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObs = new javax.swing.JTextArea();
        btEnviar = new javax.swing.JButton();
        opcaoBD = new javax.swing.JCheckBox();
        opcaoLogica = new javax.swing.JCheckBox();
        opcaoPOO = new javax.swing.JCheckBox();
        opcaoNenhuma = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(400, 400));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 182, 109));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Pesquisa de satisfação Senac Tech");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNome.setText("Nome completo");

        labelCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCurso.setText("Curso");

        grupoCursos.add(opcaoTI);
        opcaoTI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoTI.setText("Técnico de Informática");
        opcaoTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTIActionPerformed(evt);
            }
        });

        grupoCursos.add(opcaoTDS);
        opcaoTDS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoTDS.setText("Técnico em Desenvolvimento de Sistemas");
        opcaoTDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoTDSActionPerformed(evt);
            }
        });

        grupoCursos.add(opcaoAdm);
        opcaoAdm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoAdm.setText("Técnico em Administração");
        opcaoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoAdmActionPerformed(evt);
            }
        });

        labelMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMaterias.setText("Em quais matérias teve dificuldade?");

        grupoSatisfacao.add(opcaoMtSatisfeito);
        opcaoMtSatisfeito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoMtSatisfeito.setText("Muito satisfeito");
        opcaoMtSatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMtSatisfeitoActionPerformed(evt);
            }
        });

        grupoSatisfacao.add(opcaoSatisfeito);
        opcaoSatisfeito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoSatisfeito.setText("Satisfeito");
        opcaoSatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoSatisfeitoActionPerformed(evt);
            }
        });

        grupoSatisfacao.add(opcaoInsatisfeito);
        opcaoInsatisfeito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoInsatisfeito.setText("Insatisfeito");
        opcaoInsatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoInsatisfeitoActionPerformed(evt);
            }
        });

        labelNivel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNivel.setText("Nível de satisfação com o curso");

        labelObs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelObs.setText("Observações (opcional)");

        campoObs.setColumns(20);
        campoObs.setRows(5);
        jScrollPane1.setViewportView(campoObs);

        btEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        opcaoBD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoBD.setText("Banco de Dados");
        opcaoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoBDActionPerformed(evt);
            }
        });

        opcaoLogica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoLogica.setText("Lógica de Programação");
        opcaoLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoLogicaActionPerformed(evt);
            }
        });

        opcaoPOO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoPOO.setText("Prog. Orientada a Objetos");
        opcaoPOO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoPOOActionPerformed(evt);
            }
        });

        opcaoNenhuma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoNenhuma.setText("Nenhuma");
        opcaoNenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoNenhumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelObs)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(18, 18, 18)
                                .addComponent(campoNome))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNivel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelCurso)
                                            .addGap(80, 80, 80)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(opcaoTI)
                                                .addComponent(opcaoTDS)
                                                .addComponent(opcaoAdm)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(opcaoMtSatisfeito))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(opcaoSatisfeito)
                                                    .addComponent(labelMaterias)))
                                            .addGap(41, 41, 41)
                                            .addComponent(opcaoInsatisfeito)
                                            .addGap(11, 11, 11))))
                                .addGap(0, 36, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcaoLogica)
                            .addComponent(opcaoPOO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcaoBD)
                            .addComponent(opcaoNenhuma))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btEnviar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCurso)
                    .addComponent(opcaoTDS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcaoTI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcaoAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoMtSatisfeito)
                    .addComponent(opcaoSatisfeito)
                    .addComponent(opcaoInsatisfeito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMaterias)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoLogica)
                    .addComponent(opcaoBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoPOO)
                    .addComponent(opcaoNenhuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEnviar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcaoTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoTIActionPerformed

    private void opcaoTDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoTDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoTDSActionPerformed

    private void opcaoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoAdmActionPerformed

    private void opcaoMtSatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMtSatisfeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoMtSatisfeitoActionPerformed

    private void opcaoSatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoSatisfeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoSatisfeitoActionPerformed

    private void opcaoInsatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoInsatisfeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoInsatisfeitoActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        String dados = "Dados enviados para Pesquisa de Satisfação Senac Tech:\n";
        dados += "\n-----------------------------------------------------------------------------------\n\n";

        dados += labelNome.getText() + ":\n" + campoNome.getText() + "\n\n";
        dados += "-----------------------------------------------------------------------------------\n\n";

        dados += labelCurso.getText() + ":\n";

        if (opcaoTDS.isSelected()) dados += opcaoTDS.getText();
        else if (opcaoTI.isSelected()) dados += opcaoTI.getText();
        else if (opcaoAdm.isSelected()) dados += opcaoAdm.getText();
        else dados += "Nenhuma opção selecionada";

        dados += "\n\n-----------------------------------------------------------------------------------\n\n";

        dados += labelNivel.getText() + ":\n";

        if (opcaoMtSatisfeito.isSelected()) dados += opcaoMtSatisfeito.getText();
        else if (opcaoSatisfeito.isSelected()) dados += opcaoSatisfeito.getText();
        else if (opcaoInsatisfeito.isSelected()) dados += opcaoInsatisfeito.getText();
        else dados += "Nenhuma opção selecionada";

        dados += "\n\n-----------------------------------------------------------------------------------\n\n";

        dados += "Matérias que teve dificuldade:";

        if (opcaoLogica.isSelected()) dados += "\n" + opcaoLogica.getText() + " ";
        if (opcaoBD.isSelected()) dados += "\n" + opcaoBD.getText() + " ";
        if (opcaoPOO.isSelected()) dados += "\n" + opcaoPOO.getText() + " ";
        if (opcaoNenhuma.isSelected()) dados += "\n" + opcaoNenhuma.getText() + " ";

        dados += "\n\n-----------------------------------------------------------------------------------\n\n";

        dados += labelObs.getText() + ":\n";
        dados += campoObs.getText() + "\n";
        dados += "\n-----------------------------------------------------------------------------------\n\n";

        JOptionPane.showMessageDialog(null,
            dados, "Formulário enviado com sucesso!",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btEnviarActionPerformed

    private void opcaoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoBDActionPerformed

    private void opcaoLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoLogicaActionPerformed

    private void opcaoPOOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoPOOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoPOOActionPerformed

    private void opcaoNenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoNenhumaActionPerformed
        if(opcaoNenhuma.isSelected()) {
            opcaoLogica.setEnabled(false);
            opcaoLogica.setSelected(false);

            opcaoBD.setEnabled(false);
            opcaoBD.setSelected(false);

            opcaoPOO.setEnabled(false);
            opcaoPOO.setSelected(false);
        } else if(!opcaoNenhuma.isSelected()) {
            opcaoLogica.setEnabled(true);
            opcaoBD.setEnabled(true);
            opcaoPOO.setEnabled(true);
        }
    }//GEN-LAST:event_opcaoNenhumaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextArea campoObs;
    private javax.swing.ButtonGroup grupoCursos;
    private javax.swing.ButtonGroup grupoSatisfacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelMaterias;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton opcaoAdm;
    private javax.swing.JCheckBox opcaoBD;
    private javax.swing.JRadioButton opcaoInsatisfeito;
    private javax.swing.JCheckBox opcaoLogica;
    private javax.swing.JRadioButton opcaoMtSatisfeito;
    private javax.swing.JCheckBox opcaoNenhuma;
    private javax.swing.JCheckBox opcaoPOO;
    private javax.swing.JRadioButton opcaoSatisfeito;
    private javax.swing.JRadioButton opcaoTDS;
    private javax.swing.JRadioButton opcaoTI;
    // End of variables declaration//GEN-END:variables
}
